config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  resources :places, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :favourites, only: [ :create ]
    resources :visits, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :favourites, only: [ :index, :destroy ]
  resources :reviews, only: [ :destroy ]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  namespace :charts do
    get "visit-over-time"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :place
  validates :place_id, uniqueness: { scope: :user_id, message: "This place is already in your favourite list!" }
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    # @place = Place.find(params[:place_id])
    @favourites = current_user.favourites
    @surf = SportType.find_by(name: "Surf")
    @basketball = SportType.find_by(name: "Basketball")
    @calisthenics = SportType.find_by(name: "Calisthenics")
    @ping_pong = SportType.find_by(name: "Ping-Pong")
  end

  def show
    @surf = SportType.find_by(name: "Surf")
    @basketball = SportType.find_by(name: "Basketball")
    @calisthenics = SportType.find_by(name: "Calisthenics")
    @ping_pong = SportType.find_by(name: "Ping-Pong")
  end


  def create
    @user = current_user
    @place = Place.find(params[:place_id])
    @favourite = Favourite.new
    @favourite.user = @user
    @favourite.place = @place
    authorize @favourite
    if @favourite.save
      redirect_to place_path(@place), notice: "Added to favourites."
    else
      # render "places/show"
      redirect_to place_path(@place), notice: "Already on the list."
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    authorize @favourite
    @favourite.destroy
    redirect_to favourites_path, notice: "Succesfully removed."
  end

  private

  def favourite_params
    params.require(:favourite).permit(:place_id)
  end
end

app/views/favourites/_chatroom_button.html.erb
<%= link_to chatroom_path(sport_type.chatroom) do %>
  <i class="<%= sport_type.icon_name %> "></i>

  
  <p><%= sport_type.name.downcase %><p>
  <% unread_msg =  sport_type.chatroom.unread_msg(current_user) %>
  <% if unread_msg.positive? %>
    <span class="topcorner badge badge-secondary"><%= unread_msg %></span>
  <% end %>
<% end %> 

app/views/favourites/index.html.erb
  <div class="container">

    <h5 id="favourite-title">
      <span id="banner-typed-text"></span>
    </h5>

  <div id="chat-section-favourites">
    <p>💬 Join one of the chat rooms:</p>

      <div id="chat-icons">

        <div id="chat-icon">
          <%= render "chatroom_button", sport_type: @basketball %>
        </div>

        <div id="chat-icon">
          <%= render "chatroom_button", sport_type: @ping_pong %>
        </div>

        <div id="chat-icon">
          <%= render "chatroom_button", sport_type: @calisthenics %>
        </div>

        <div id="chat-icon">
          <%= render "chatroom_button", sport_type: @surf %>
        </div>
      </div>
    </div>
  </div>

  <div id="background-favourites-cards">
  <div class="container">

    <h5 id="favourite-title2">Your favourites</h5>

    <% @favourites.each do |favourite| %>
      <div class="card-trip">

        <% if (favourite.place).photos.attached? %>
          <%= cl_image_tag (favourite.place).photos.first.key, crop: :fit %>
        <% else %>
          <%= image_tag 'sports_img.jpg', crop: :fill %>
        <% end %>

        <div class="card-trip-infos">
          <div>
            <h2><%= link_to (favourite.place).name, place_path(favourite.place) %></h2>
            <p><strong><%= (favourite.place).address %></strong></p>
          </div>
            <%= link_to favourite_path(favourite),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
          <i class="fillcrown fas fa-crown p-2"></i>
          <% end %>
        </div>

      </div>
    <% end %>

  </div>
</div>