config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  resources :places, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :favourites, only: [ :create ]
    resources :visits, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :favourites, only: [ :index, :destroy ]
  resources :reviews, only: [ :destroy ]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  namespace :charts do
    get "visit-over-time"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "EquRent.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My favourites", favourites_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_tabbar.html.erb
<nav class="tabbar">
    <ul>
        <li>
           <%= link_to root_path do %>
                <div>
                    <span>
                        <svg>
                            <i class="fas fa-home"></i>
                        </svg>
                    </span>
                    <span>
                        <svg>
                            <i class="fas fa-home"></i>
                        </svg>
                    </span>
                </div>
                <strong>Home</strong>
            <% end %>
        </li>
        <li>

            <%= link_to places_path do %>

                <div>
                    <span>
                        <svg>
                            <i class="fas fa-search"></i>
                        </svg>
                    </span>
                    <span>
                        <svg>
                            <i class="fas fa-search"></i>
                        </svg>
                    </span>
                </div>

                <strong>Search</strong>

            <% end %>
        </li>
        <li>
            <%= link_to favourites_path do %>
                <div>
                    <span>
                        <svg>
                           <i class="fas fa-crown"></i>
                        </svg>
                    </span>
                    <span>
                        <svg>
                           <i class="fas fa-crown"></i>
                        </svg>
                    </span>
                </div>
                <strong>Favourites</strong>
            <% end %>
        </li>
        <li>

            <%= link_to dashboard_path do %>

                <div>
                    <span>
                        <svg>
                            <i class="far fa-user"></i>
                        </svg>
                    </span>
                    <span>
                        <svg>
                           <i class="far fa-user"></i>
                        </svg>
                    </span>
                </div>
                <strong>Dashboard</strong>

            <% end %>

        </li>
    </ul>
</nav>