config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  resources :places, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :favourites, only: [ :create ]
    resources :visits, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :favourites, only: [ :index, :destroy ]
  resources :reviews, only: [ :destroy ]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  namespace :charts do
    get "visit-over-time"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<div class="container p-2">
  <br>
  <h5 id="favourite-title">
    <span id="banner-typed-text"></span>
  </h5>

  <div class="d-flex flex-column justify-content-center">
    <div class="form-control d-flex justify-content-center"><h5>Made by</h5></div>
    <div class="form-control d-flex justify-content-center mt-1"><h5>Andrea</h5></div>
    <div class="form-control d-flex justify-content-center mt-1"><h5>Armen</h5></div>
    <div class="form-control d-flex justify-content-center mt-1"><h5>Isabella</h5></div>
    <div class="form-control d-flex justify-content-center mt-1"><h5>Tea</h5></div>
    <div class="form-control d-flex justify-content-center pt-2 mt-1 fas fa-heart"><h5></h5></div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container p-4 mt-1">
  <form method="post" data-form-title="CONTACT US">
  <input type="text" data-form-email="true">
  <h3>Contact<strong> Equ</strong>Spot</h3>
  <br>
  <div class="form-group">
    <input class="form-control" name="first_name" id="messages-bordered-a" placeholder="First Name" data-form-field="first_name">
  </div>
  <div class="form-group">
    <input class="form-control" name="last_name" id="messages-bordered-a" placeholder="Last name" data-form-field="last_name">
  </div>
  <div class="form-group">
    <input type="email" class="form-control" id="messages-bordered-a" name="email" required="" placeholder="E-Mail *" data-form-field="Email">
  </div>
  <div class="form-group">
    <textarea class="form-control" name="message" id="messages-bordered-a" required="" placeholder="Message *" rows="7" data-form-field="Message"></textarea>
  </div>
  <div class="p-1">
    <button type="submit"  class="btn btn-outline-danger w-100" id="messages-bordered-a">SEND</button>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container p-3 mt-4">

  <div class="d-flex" id="welcome">
    <h5>Welcome <%= @user.first_name %>!</h5>
  </div>

  <div class="d-flex justify-content-between pr-3 mt-5">
    <div>
      <% if current_user.profile_img.attached? %>
        <%= cl_image_tag current_user.profile_img.key, class: "avatar-andrea profile-img" %>
      <% else %>
        <i class="fas fa-user-circle fa-3x"></i>
      <% end %>
    </div>
    <div id="profile-top">
      <p><strong>Total check-ins</strong></p>
      <span><strong><%= current_user.visits.count %></strong></span>
    </div>
    <div id="profile-top">
      <p><strong><%= link_to 'Favourites', favourites_path %></strong></p>
      <span><strong><%= current_user.favourites.count %></strong></span>
    </div>
  </div>

  <div class="mt-5">
    <p>You´ve had <strong><%= @visit_this_month %></strong>
    activities this month. This is a change in activity of
    <strong><%= @percentage_change_month %>% since last month.</strong><br/>
    <strong><%= @motivational_msg %></strong></p>
  </div>

  <br>

  <div class="mt-3">
    <p><strong>Your activities</strong></p>
    <%= line_chart @user.visits.group_by_month(:created_at).count, width: "100%", height: "200px", colors: ["#2B5D6C"], points: false%>
    <% @user.visits.last(1).each do |visit| %>
    <p><br><em>Last visit: </em><%= visit.created_at.strftime("%m/%d/%Y")%>: <%= link_to visit.place.name, place_path(visit.place) %></p>
    <% end %>
  </div>

  <br>

  <div class="mt-4">
    <p><strong>Most frequent activity</strong></p>
    <%= bar_chart @user.sport_types.group(:name).count, width: "100%", height: "200px", colors: ["#FF8882", "#2B5D6C"], legend: false %>
  </div>

  <br>

  <div class="mt-5">
    <p><strong>Your top 3 places</strong></p>
    <%= pie_chart @user.places.group(:name).limit(3).count, width: "100%", height: "200px", colors: ["#FF8882", "#2B5D6C", "#5db0ca"], legend: "bottom" %>
    <br>
  </div>
</div>

<br>

<div class="d-flex p-2 form-control justify-content-around box-dark">
  <div class="form-group mt-3">
    <p><%= link_to "Account", profile_path %></p>
  </div>
  <div class="form-group mt-3">
    <p><%= link_to "Contact", contact_path %></p>
  </div>
  <div class="form-group mt-3">
    <p><%= link_to "About", about_path %></p>
  </div>
  <div class="form-group mt-3">
    <p><%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>
        <% end %></p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner d-flex justify-content-center" id="parent-home" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= image_path 'skate_pic.jpg', crop: :fill %>');">
</div>
  <div class="container">
    <div class="card" id="home-card">
        <div class="card-body">
          <h5 class="card-title"><strong>Equ</strong>Spot</h5>
          <p class="card-text mt-3">Find all the free outdoor activities available near you.</p>
          <%= link_to "Search by sport category", places_path, class: "button btn btn-primary mt-1 w-100" %>
        </div>
    </div>
  </div>

<br>

<div class= "container">
  <div id="about-txt-a">
    <p>On EquSpot, you can find all the free outdoor activities available near you.
    You can select one particular sport or activity and search or
    just explore through the map.</p>
  </div>
</div>

<div id="background_home">
  <div class="container">
    <div id="map"
      class="mb-0 p-2"
      style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div class="m-1">
      <div class="mt-4 mb-4">
        <h5 class="text-white">Most popular</h5>
      </div>
        <% Place.where.not(visits_count: nil).order("visits_count desc").limit(10).each do |place| %>
        <div class="card-trip">
          <% if place.photos.attached? %>
            <%= cl_image_tag place.photos.first.key, crop: :fit %>
          <% else %>
            <%= image_tag 'sports_img.jpg', crop: :fill %>
          <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to place.name, place_path(place) %></h2>
            <p id="place-address-card"><strong><%= place.address %></strong></p>
            <p><i><%= place.description %></i></p>
            <div>
              <select data-rating= <%= place.average_rating %> data-id= <%= place.id %> name="" class="review-rating" id= <%= "review-#{place.id}" %> >
                <option value="">0</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
          </div>
          <div>
            <%= link_to place_favourites_path(place), method: :post, params: { "favourite[place_id]" => place.id } do %>
              <i class="fas fa-crown"></i>
            <% end %>
          </div>
        </div>
      </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/pages/profile.html.erb
<div class="container p-4 mt-3">
  <div class="p-1">

    <div class="d-flex justify-content-between">
      <div class="mt-4 p-1">
        <h3>Your account</h3>
      </div>
      <div class="p-1">
        <% if current_user.profile_img.attached? %>
          <%= cl_image_tag current_user.profile_img.key, class: "avatar-andrea profile-img" %>
        <% else %>
          <i class="p-1 fas fa-user-circle fa-5x"></i>
        <% end %>
      </div>
    </div>

      <br>
      <h6>First name:</h6>
      <p><%= current_user.first_name%></p>
      <p></p>
      <br>
      <h6>Last name:</h6>
      <p><%= current_user.last_name%></p>
      <br>
      <h6>E-Mail:</h6>
      <p><%= current_user.email%></p>
    </div>


    <div>
<!--
    <div class="mt-4 p-1" >
      <h6 class="btn btn-outline-primary mt-1 p-3 w-100" id="messages-bordered-a">Add a spot
      </h6>
    </div> -->
      <br><br>

    <div>
      <h5 class="ml-2"><%= current_user.places.count %> Spots</h5>

      <div class="mt-4">
        <div class="btn btn-a btn-outline-light mt-1 p-4 w-100">
          <%= link_to new_place_path do %>
          <h6 class="mt-2 blue-plus far fa-plus-square fa-lg" id="fa-plus-a"></h6>
          <% end %>
        </div>
      </div>
    </div>

    <div>
      <div class="mt-3 text-capitalize">
        <% @user.places.each do |place| %>

        <div class="mb-2 mt-3 p-2" id="messages-bordered-a">
          <div class="p-2">
            <div class="d-flex justify-content-between">
              <h5><%= link_to place.name, place_path(place) %></h5>
              <div class="d-flex">
                <p class="fa fa-edit p-1"> <%= link_to "", edit_place_path(place) %></p>
                <div class="p-1"></div>

                <div id="show-bucket" >
                  <%= link_to place_path(place),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>
              </div>
            </div>

            <div>
            <p class="grey-text"><%= place.address %></p>
            <%= place.description %>
            </div>
          </div>
        </div>

          <% end %>
        </div>
      </div>
    </div>

      <br>

    <div>
      <div class="mt-4 p-2">
        <h5 class="ml-2"><%= current_user.reviews.count %> Reviews</h5>

        <div class="mt-3">
          <% @user.reviews.each do |review| %>

            <div class="mb-2 mt-3 p-2" id="messages-bordered-a">
              <div class="mb-2 p-1">
                <select data-rating= <%= review.rating %> data-id= <%= review.id %> name="" class="review-rating" id= <%= "review-#{review.id}" %> >
                  <option value="">0</option>
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                </select>
              </div>

              <div class="d-flex p-2 justify-content-between">
                <div id="show-rating">
                  <%= review.content %>
                </div>

                <div id="show-bucket" >
                  <%= link_to review_path(review),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>
              </div>
            </div>

          <% end %>
        </div>
      </div>

      <div class="p-3"><br><br><br>
        <p><%= link_to 'Change your profile', edit_user_registration_path %></p>
        <p class="mb-0">Unhappy? <%= link_to "Delete your account", user_registration_path, data: { confirm: "Are you sure?" }, method: :delete %></p>
        <p class="mt-3"><%= link_to destroy_user_session_path, method: :delete do %><i class="fas fa-sign-out-alt"></i> Log out
          <% end %></p>
      </div>

    </div>
  </div>
</div>