config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard', as: :dashboard
  get 'profile', to: 'pages#profile', as: :profile
  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
  resources :places, only: [ :index, :new, :create, :show, :edit, :update, :destroy ] do
    resources :favourites, only: [ :create ]
    resources :visits, only: [ :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :favourites, only: [ :index, :destroy ]
  resources :reviews, only: [ :destroy ]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  namespace :charts do
    get "visit-over-time"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :visits, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :sport_combinations, dependent: :destroy
  has_many :sport_types, through: :sport_combinations
  has_many_attached :photos
  validates :name, presence: true, uniqueness: true
  validates :description, length: { maximum: 250, message: "no longer than 250 characters." }
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  def average_rating
    ratings = reviews.map { |review| review.rating }
    if ratings.length.zero?
      0
    else
      ratings.sum / ratings.length
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_place, only: [ :show, :edit, :update ]

  def index
    @places = policy_scope(Place)

    # search bar - by sport
    @dropdown = SportType.all
    if params[:query].present? && params[:sport][:id].present?
      @places = Place.joins(:sport_combinations).where("places.address ILIKE ? AND sport_combinations.sport_type_id = ?", "%#{params[:query]}%", params[:sport][:id].to_i)
    elsif params[:sport].present? && !params[:sport][:id].blank?
      sql_query = "sport_types.id = :sport"
      @places = Place.joins(:sport_types).where(sql_query, sport: params[:sport][:id].to_i)
    elsif params[:query].present? && params[:sport][:id].blank?
      sql_query = "address ILIKE :query"
      @places = Place.where(sql_query, query: "%#{params[:query]}%")
    else
      @places = Place.all
    end
    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window: render_to_string(partial: "info_window", locals: { place: place }),
        image_url: helpers.asset_url("#{place.sport_types.first.name}.png")
      }
    end
  end

  def show
    set_place
    @visits_count = @place.visits.where("created_at > ?", 180.minutes.ago).count
    if @visits_count.zero?
      @busyness = "No one is currently here."
    elsif @visits_count == 1
      @busyness = "1 person is here."
    else
      @busyness = "#{@visits_count} people are here."
    end
    @reviews = @place.reviews
    @ratings = @reviews.map { |review| review.rating }
    if @ratings.length.zero?
      @average_rating = 0
    else
      @average_rating = @ratings.sum / @ratings.length
    end
    authorize @place
    @markers = [{
        lat: @place.latitude,
        lng: @place.longitude,
        info_window: render_to_string(partial: "address_window", locals: { place: @place }),
        image_url: helpers.asset_url("#{@place.sport_types.first.name}.png")
      }]
  end

  def new
    @place = Place.new
    authorize @place
  end

  def create
    @user = current_user
    @place = Place.new(place_params)
    @place.user = @user
    authorize @place
    if @place.save
      redirect_to places_path, notice: "Spot was successfully created."
    else
      render :new
    end
  end

  def edit
    authorize @place
  end

  def update
    authorize @place
    if @place.update(place_params)
      redirect_to place_path(@place)
    else
      render :edit
    end
  end

  def destroy
    set_place
    authorize @place
    @place.destroy
    redirect_to profile_path, notice: "Spot successfully removed."
  end

  private

  def set_place
    @place = Place.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :address, :description, photos: [], sport_type_ids: [])
  end
end

app/views/places/_address_window.html.erb
<div class="text-left text-capitalize mt-3">
  <h6 class="m-2"><%= place.address %></h6>
</div>

app/views/places/_form.html.erb
<div class="container p-4 mt-4">
  <h5 class="p-3 ml-1">Add a playground</h5>
  <div class="p-2">
    <%= simple_form_for(@place, remote:true) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="mb-0 mt-3" id="messages-bordered-b">
        <div class="p-2 mt-1">
          <%= f.input :name, required: :true, as: :text, input_html: {rows: 2}, placeholder: 'Name of the spot', label:false %>
        </div>
        <div class="p-2">
          <%= f.input :description, required: :true, as: :text, input_html: {rows: 5}, placeholder: 'Enter a short description of the spot', label:false %>
        </div>

        <div class="p-2">
          <%= f.input :address, required: :true, as: :text, input_html: {rows: 2}, placeholder: 'Edelweissweg 10, Munich', label:false %>
        </div>

        <div class="d-flex p-3">
          <div id="upload-button" class="upload-button btn-a btn btn-outline-primary w-100">
            Upload photos
          </div>
          <div hidden>
            <%= f.input :photos, as: :file, input_html: { multiple: true }, label:false %>
          </div>
          <div class="w-100"></div>
        </div>

        <div class="p-4 mt-1">
          <%= f.association :sport_types, required: :true, as: :check_boxes %>
        </div>
      </div>

      <br>

      <div class="btn btn-a btn-outline-light mt-1 p-3 w-100">
        <%= f.button :submit %>
      </div>

    <% end %>
  </div>
</div>

app/views/places/_info_window.html.erb
<div class="text-left text-capitalize mt-3">
  <h6 class="m-2"><%= link_to place.name, place_path(place) %></h6>
  <p class="m-2"><%= place.address %></p>
</div>

app/views/places/edit.html.erb
<%= render 'form' %>

app/views/places/index.html.erb
<body id="background_index">
  <div id="map"
    style="width: 100%; height: 450px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  
  <div class="container mt-1">

    <form autocomplete="off">
      <div class="m-1">
        <div>
          <%= form_tag places_path, method: :get do %>
          <%= text_field_tag :query, params[:query],
          placeholder: "Search by location", class: "p-3" %>
        </div>
        <div class="mt-2">
        <div class="form-row mt-1 mb-3 align-middle">
          <div class="col-8 mt-1">
            <%= collection_select :sport, :id, @dropdown, :id, :name, include_blank: true %>
          </div>

          <div class="col-4">
            <%= submit_tag "Find", class: "btn btn-primary w-100", id: "index-show-btn2" %>
          </div>
        </div>
        </div>
          <% end %>
      </div>
    </form>

  <% @places.each do |place| %>
    <div class="card-trip">
      <% if place.photos.attached? %>
        <%= cl_image_tag place.photos.first.key, crop: :fit %>
      <% else %>
        <%= image_tag 'sports_img.jpg', crop: :fill %>
      <% end %>
    <div class="card-trip-infos"> 
      <div>
        <h2><%= link_to place.name, place_path(place) %></h2>
        <p id="place-address-card"><strong><%= place.address %></strong></p>
        <p><i><%= place.description %></i></p>
        <div>
          <select data-rating= <%= place.average_rating %> data-id= <%= place.id %> name="" class="review-rating" id= <%= "review-#{place.id}" %> >
            <option value="">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </div>
      </div>
      <div>
        <%= link_to place_favourites_path(place), method: :post, params: { "favourite[place_id]" => place.id } do %>
          <i class="fas fa-crown"></i>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>


      <div>
        <div class="btn btn-primary w-100" id="index-show-btn">
          <%= link_to new_place_path do %>
           <i class="fas fa-plus fa-lg"></i>
          <% end %>
        </div><div class="mt-3"></div>
      </div>
    </div>
  </div>
</body>

app/views/places/new.html.erb
<%= render 'form' %>

app/views/places/show.html.erb
<div class="weather-buffer">
  <div class="weather">
    <div class="container">
      <p id="weather-item" data-latitude="<%= @place.latitude %>" data-longitude="<%= @place.longitude %>" data-name="<%= @place.name %>" data-apikey="<%=ENV['WEATHER_API_KEY']%>"></p>
    </div>
  </div>
</div>

  <div class="parent-show" id="show-img" style="background-image: url('<%= cl_image_path @place.photos.first.key, crop: :fit %>');">
  </div>
      <div class="container">
            <div class="card mb-3" id="show-card">
              <div class="card-body">
                <div id="show-card-top">
                  <h5><%= @place.name %></h5>
                  <%= link_to place_favourites_path(@place), method: :post, params: { "favourite[place_id]" =>  @place.id } do %>
                    <% if user_signed_in? && current_user.favourites.find_by(place: @place).present? %>
                      <i class="fillcrown fas fa-crown"></i>
                    <% else %>
                      <i class="emptycrown fas fa-crown"></i>
                    <% end %>
                  <% end %>
                </div>
                <div id="place-description">
                  <p><%= @place.description %></p>
                </div>
                <div id="show-card-bottom">
                  <div>
                    <i class="fas fa-users mr-1"></i>
                    <em><%= @busyness%></em>
                  </div>
                  <div>
                    <%= link_to place_visits_path(@place), method: :post do %>
                      <i class="far fa-check-square fa-lg mb-1"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
    </div>

<div class="container">


  <div id="place-edit">
    <% if @place.user == current_user %>
      <div>
        <em>You created this place<em>
      </div>
      <div id="place-edit-btn">
        <%=  link_to edit_place_path(@place)do %>
          <i class="fas fa-pen fa-lg"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div id="map"
    style="width: 100%; height: 180px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
 
<% @place.photos.first(5).each_with_index do |photo, i| %>
  <div class="images-show-grid-1">
    <% next if i.zero? %>
    <%= cl_image_tag photo.key, class: 'grid-img-1' %>
  </div>
<% end %>

  <div id="review-show">

    <div class="card rating-direction">

        <select data-rating="<%= @average_rating %>" data-id="total" name="" class="review-rating" id="review-total">
          <option value="">0</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>

        <p class="m-2">(<%= @reviews.count %>)</p>

    </div>

    <% @place.reviews.order(created_at: :desc).limit(3).each do |review| %>
      <div id="show-flex">
        <div id="show-rating">
          <select data-rating= <%= review.rating %> data-id= <%= review.id %> name="" class="review-rating" id= <%= "review-#{review.id}" %> >
            <option value="">0</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
        </div>
        <div>
           <%= review.content %>
        </div>
        <div id="show-bucket">
          <%= link_to review_path(review),

            method: :delete,
            data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
        </div>

      </div>
    <% end %>
  </div>

  <div id="btn-show-end">
    <%= link_to 'Leave a review', new_place_review_path(@place), class: "btn btn-primary w-100" %></p>
    <%= link_to "Chat", chatroom_path(@place.sport_types.first.chatroom), class: "btn btn-primary w-100" %>
  </div>
</div>